theme: jekyll-theme-minimal
title: Abby's homepage
description: This is a basic Github web Browser for Abigail Rankin's GitHub profile!!

paragraph: Hello! my name is Abigail rankin! I'm a student at BSU and I'm also a second year. I know at least some programming from my old school which I transfered from. Though they use python instead of JavaScript.
